#!/usr/bin/env bash
# Displays a message when receiving a SIGTERM signal

term_handler() {
    echo "I am invincible!!!"
}

trap term_handler SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2 &
    wait $!
done
