#!/usr/bin/env bash
# Displays To infinity and beyond and handles SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2 &   # 1. Puts sleep into the background
    wait $!     # 2. Waits for the background process ($!)
done
